version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4
    restart: unless-stopped
    ports:
      - 6379:6379

  user_service:
    build: ./userService
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./api_specs:/app/api_specs

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbdata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 5

  site_service:
    build: ./confService
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    volumes:
      - ./api_specs:/app/api_specs