version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  user_service:
    build: ./userService
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./api_specs:/app/api_specs
  site_service:
    build: ./confService
    ports:
      - "8001:8001"
    volumes:
      - ./api_specs:/app/api_specs